[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "openTEPES"
dist-name = "openTEPES"
author = "IIT-EnergySystemModels"
author-email = "andres.ramos@comillas.edu"
home-page = "https://pascua.iit.comillas.edu/aramos/openTEPES/index.html"
classifiers = [
"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
"Programming Language :: Python :: 3.8",]
requires-python = ">=3.8"
description-file = "README.md"

[tool.flit.scripts]
scripts = "scripts.openTEPES_run:main"
